"""Every sentence the simulation can show the agent. Kept in one place so tests can scan it.

Wording rule: say what happened. Never say why, and never say what to do. Exceptions, each
because a model could not tell why from what it saw (see DECISIONS.md): NOT_MOVED_DRY states the
rule for moving up and down, and with rule_notes on, NOT_MADE_EXACT, NOT_MADE_STATION,
OBS_NO_HEAL, NOT_PLANTED, NOT_EMPTY_SOIL and OBS_WET_RULE say why a craft or planting failed, or why health is
not rising or food is falling fast, and DIED_CHEST_NOTE says what a death does not take.
"""

MOVED = "Moved {n} {cells} {dir}."
NOT_MOVED = "You did not move."
NOT_MOVED_DRY = "You did not move. Up and down only work in water."
BLOCKED_BY = " Blocked by {things}."
BLOCKED_CELL = "{name} at ({x},{y},{z})"
BLOCKED_CREATURE = "{kind} #{id}"
GOT = "Got {n} {item}."
NOT_BROKEN = "The block did not break."
NOTHING_THERE = "Nothing is there."
TOO_FAR = "Too far."
TOOL_BROKE = " The {tool} broke."
PLACED = "Placed {item} at ({x}, {y}, {z})."
NOT_PLACED = "The {item} was not placed."
NOT_EMPTY = "The cell is not empty."
IN_YOUR_CELL = "You are in that cell."
MADE = "Made {n} {item}."
NOT_MADE = "Nothing was made."
NOT_MADE_EXACT = "Nothing was made. Nothing is made from exactly these items and amounts."
NOT_MADE_STATION = "Nothing was made. No {station} within {r} cells."
ATE = "Ate 1 {item}."
NOT_EATEN = "The {item} was not eaten."
HIT = "Hit {kind} #{id}."
HIT_GONE = "Hit {kind} #{id}. It is gone."
NO_CREATURE = "No creature #{id} within reach."
WAITED = "Waited {n} {steps}."
HIT_YOU = " {kind} #{id} at ({x}, {y}, {z}) hit you."
NO_ITEM = "No such item in inventory."
NOT_ENOUGH = "Not enough {item} in inventory."
UNKNOWN_ACTION = "Unknown action."
# long_actions: goto and repeat
GOTO_THERE = "Walked {n} {cells}. You are beside it, at ({x}, {y}, {z})."
GOTO_ALREADY = "You are already beside it."
GOTO_PART = "Walked {n} {cells}, now at ({x}, {y}, {z}). {why}"
GOTO_NO_WAY = "There is no way further on foot."
GOTO_HURT = "Stopped: you were hurt."
GOTO_NEW = "Stopped: something new came into view."
GOTO_LIMIT = "Stopped after {n} steps, not there yet."
GOTO_GONE = "It is gone."
GOTO_BLOCKED = "Stopped: the way was blocked."
REPEAT_DONE = " Done {n} of {m} times."
BAD_ARGS = "Bad arguments."
NOTHING = "Nothing happened."
NO_ROOM = "No room in inventory."
NO_ROOM_FOR = " No room for {n} {item}."
NO_CHEST = "No {chest} at ({x}, {y}, {z})."
CHEST_FULL = "No room in the {chest}."
CHEST_NOT_EMPTY = "The {chest} is not empty."
NOT_IN_CHEST = "Not enough {item} in the {chest}."
NOT_STORED = "The {item} was not stored."
STORED = "Stored {items}."
TOOK = "Took {items}."
DROPPED = "Dropped {items}."
JUMPED = "Moved up 1 cell. Placed {item} at ({x}, {y}, {z})."
NOT_PLANTED = "The {item} was not placed. It needs {soil} under it and {water} within {r} cells."
NOT_EMPTY_SOIL = ("The cell is not empty: ({x}, {y}, {z}) is {block}. {item} go in the empty cell above "
                  "the {block}, ({x}, {y1}, {z}).")
HAIL_HIT = " Hail hit you."
NO_BED = "No {bed} within {r} cells."
NOT_SLEPT_SKY = "You did not sleep. The sky is bright."
NOT_SLEPT_CREATURE = "You did not sleep. {kind} #{id} is at ({x}, {y}, {z})."
SLEPT = "Slept {n} {steps}. Your respawn point is the {bed} at ({x}, {y}, {z})."
CUT_SHORT = " Cut short by your next action."
SAID = 'Said "{text}".'
HEARD_BY = " Heard by {who}."
HEARD_BY_NONE = " No one heard it."
AGENT_REF = "agent #{id}"
GAVE = "Gave {items} to agent #{id}."
NO_AGENT = "No agent #{id} within {r} cells."
NO_ROOM_THEIRS = "No room in the inventory of agent #{id}."

DIED_RESPAWN = "You died. Cause: {cause}. You are back at the starting point. Your items are gone."
DIED_RESPAWN_BED = ("You died. Cause: {cause}. You are back beside your {bed} at ({x}, {y}, {z}). "
                    "Your items are gone.")
DIED_END = "You died. Cause: {cause}."
DIED_CHEST_NOTE = " What is in a {chest} is not lost."
DIED_BED_NOTE = " Sleeping at a {bed} makes you come back beside it."
OBS_CLOSED = "you are in a closed space of {n} floor cells: no open path for creatures leads outside"

OBS_HEADER = "step {t} | day {day} | light {light} | sky {sky}"
OBS_WEATHER = " | weather {weather}"
OBS_WET = "{what} is falling on you"
OBS_WET_RULE = "while rain falls on you, food drops {m} times as fast and health does not rise"
OBS_RESPAWN = "respawn point: {bed} at ({x},{y},{z})"
OBS_SELF = "you are agent #{id}"
OBS_HEARD = "since you last looked:"
OBS_SAID = '  agent #{id} at ({x},{y},{z}) said: "{text}"'
OBS_GIVEN = "  agent #{id} at ({x},{y},{z}) gave you {items}"
OBS_POSITION = "position ({x}, {y}, {z}), head at ({x}, {hy}, {z})"
OBS_OPEN_BESIDE = "open cells touching you: {cells}"
OBS_OPEN_BESIDE_ONE = "{where} ({x},{y},{z})"
OBS_OPEN_BESIDE_ALL = "all 9 (4 sides at feet and at head level, and above the head)"
OBS_OPEN_BESIDE_NONE = "none"
OBS_VITALS = "health {h}/{hm} | food {f}/{fm} | air {a}/{am}"
OBS_VITALS_BEFORE = "health {h}/{hm} ({h0} at step {t0}) | food {f}/{fm} ({f0} at step {t0}) | air {a}/{am}"
OBS_NO_HEAL = "health does not rise while food is under {n}"
OBS_MADE = "things you have made: {items}"
OBS_PLACED = "things you have placed: {items}"
OBS_PLACED_ONE = "{name} at {coords}"
OBS_PLACED_CHEST = "{name} at ({x},{y},{z}) holds {items}"
OBS_PLACED_MORE = " and {n} more"
OBS_MADE_ONE = "{inputs} -> {output}"
OBS_MADE_COUNT = "{c} {name}"
OBS_INVENTORY = "inventory: {items}"
OBS_INVENTORY_SLOTS = "inventory ({used} of {limit} slots): {items}"
OBS_CHEST = "  {chest} at ({x},{y},{z}) holds: {items}"
OBS_EMPTY = "empty"

# recipe_book: the whole craft table, shown once in the system prompt.
BOOK_HEADER = "Everything that can be made with craft:"
BOOK_LINE = "{inputs} -> {output}{station}"
BOOK_STATION = " (with a {station} within {r} cells)"
BOOK_FUEL = "{c} {a} or {b}"
BOOK_USE_HEADER = "What some things do:"
BOOK_USE_BED = ("{bed}: sleep with a {bed} within {r} cells, from dusk to dawn; while it stands, after a death "
                "you come back beside the {bed} you last slept at.")
BOOK_USE_CHEST = ("{chest}: once placed it holds up to {n} slots of items (no tools), put in with store and taken out "
                  "with take; what is in it stays when you die; a {chest} with items in it does not break.")
BOOK_USE_DOOR = ("{door}: once placed it fills the cell above too if that is empty (two cells high); agents walk "
                 "through it and creatures do not.")
BOOK_USE_TORCH = "{torch}: no zombies appear within {r} cells of a placed {torch}; it lights cells within {l}."
BOOK_USE_ROOF = ("rain and hail fall on you when no block above your head shuts out the sky ({leaves} do not); "
                 "under a roof it is dark without a {torch} near.")
BOOK_GROW_HEADER = "What grows:"
BOOK_USE_FOOD = "food: eating 1 restores {values}; food drops by 1 every {d} steps{rain}."
BOOK_USE_FOOD_RAIN = " ({m} times as fast while rain falls on you)"
BOOK_GROW = ("{seeds} placed with place in an empty cell on {soil} (the cell one higher than that block), with {water} within {r} cells sideways (level "
             "with that block or up to 2 below), become a {sprout}. A {sprout} turns into {wheat} after {n} steps "
             "(rain on it counts double). A {wheat} block is ripe: mining it gives {w} {wheat} and {s} or more "
             "{seeds}. Mining a {sprout} gives its {seeds} back. Mining {grass} sometimes gives {seeds}. Each {sprout} "
             "grows on its own, so several can grow at once.")
OBS_USES = "{name} ({n} uses left)"
OBS_USES_MANY = "{name} x{c} ({n} uses left)"
OBS_COUNT = "{name} x{c}"
OBS_LAST = "last action: {action}. Result: {result}"
OBS_CLOSE = "close (within {r} cells):"
OBS_VIEW = "in view (within {r} cells):"
OBS_OPEN_ABOVE = "  open air above your head, from ({x},{y},{z}) up"
OBS_BLOCK_ABOVE = "  {name} above your head at ({x},{y},{z})"
OBS_FEW = "  {name}: {coords}"
OBS_MANY = "  {name}: {n} seen, nearest {coords}"
OBS_ONE = "  {name}: nearest {coords}"
OBS_NONE = "  nothing"
OBS_CREATURES = "creatures:"
OBS_CREATURE = "  {kind} #{id} at ({x},{y},{z})"

TEMPLATES = [v for k, v in sorted(globals().items()) if k.isupper() and isinstance(v, str)]
