"""Every sentence the simulation can show the agent. Kept in one place so tests can scan it.

Wording rule: say what happened. Never say why, and never say what to do.
"""

MOVED = "Moved {n} {cells} {dir}."
NOT_MOVED = "You did not move."
GOT = "Got {n} {item}."
NOT_BROKEN = "The block did not break."
NOTHING_THERE = "Nothing is there."
TOO_FAR = "Too far."
TOOL_BROKE = " The {tool} broke."
PLACED = "Placed {item} at ({x}, {y}, {z})."
NOT_PLACED = "The {item} was not placed."
NOT_EMPTY = "The cell is not empty."
MADE = "Made {n} {item}."
NOT_MADE = "Nothing was made."
ATE = "Ate 1 {item}."
NOT_EATEN = "The {item} was not eaten."
HIT = "Hit {kind} #{id}."
HIT_GONE = "Hit {kind} #{id}. It is gone."
NO_CREATURE = "No creature #{id} within reach."
WAITED = "Waited {n} {steps}."
NO_ITEM = "No such item in inventory."
NOT_ENOUGH = "Not enough {item} in inventory."
UNKNOWN_ACTION = "Unknown action."
BAD_ARGS = "Bad arguments."
NOTHING = "Nothing happened."

DIED_RESPAWN = "You died. Cause: {cause}. You are back at the starting point. Your items are gone."
DIED_END = "You died. Cause: {cause}."

OBS_HEADER = "step {t} | day {day} | light {light}"
OBS_POSITION = "position ({x}, {y}, {z})"
OBS_VITALS = "health {h}/{hm} | food {f}/{fm} | air {a}/{am}"
OBS_INVENTORY = "inventory: {items}"
OBS_EMPTY = "empty"
OBS_USES = "{name} ({n} uses left)"
OBS_USES_MANY = "{name} x{c} ({n} uses left)"
OBS_COUNT = "{name} x{c}"
OBS_LAST = "last action: {action}. Result: {result}"
OBS_CLOSE = "close (within {r} cells):"
OBS_VIEW = "in view (within {r} cells):"
OBS_OPEN_ABOVE = "  open air above you"
OBS_BLOCK_ABOVE = "  {name} above you at ({x},{y},{z})"
OBS_FEW = "  {name}: {coords}"
OBS_MANY = "  {name}: {n} seen, nearest {coords}"
OBS_ONE = "  {name}: nearest {coords}"
OBS_NONE = "  nothing"
OBS_CREATURES = "creatures:"
OBS_CREATURE = "  {kind} #{id} at ({x},{y},{z})"

TEMPLATES = [v for k, v in sorted(globals().items()) if k.isupper() and isinstance(v, str)]
